### ISSUE TITLE
Access to MOC CNV cluster

### ISSUE THREAD

**Issue by eletonia** [open-infrastructure-labs/moc-cnv-sandbox#7]
Hi can you give me access to the MOC CNV cluster? I'm on the IBM Research team working on the open source project Mesh for Data and we would like to see how it can integrate with Open Data Hub
My email is tonia.elengikal@ibm.com

**Comment by durandom** [comment]
@eletonia we need a google account for onboarding
@larsks do we want to hold this back until we figured out https://github.com/open-infrastructure-labs/ops-issues/issues/1 ?

**Comment by eletonia** [comment]
@durandom You can use elentonia@gmail.com then

**Comment by tumido** [comment]
PR pending https://github.com/operate-first/apps/pull/104

**Comment by tumido** [comment]
Ticket resolved :tada:

Sorry for the delay, we're still ironing out the process.

We've created for you:
- a namespace [`mesh-for-data`](https://console-openshift-console.apps.cnv.massopen.cloud/k8s/cluster/projects/mesh-for-data) to begin with (you can request additional ones via issue in this repo or via PR [here](https://github.com/operate-first/apps/tree/master/namespaces/overlays/moc))
- a user group `mesh-for-data` including you for now (additional users can be requested in here or added via PR [here](https://github.com/operate-first/apps/blob/master/namespaces/overlays/moc/mesh-for-data/group.enc.yaml))

To access the cluster, please follow [this documentation](https://www.operate-first.cloud/operators/moc-cnv-sandbox/docs/about-the-cluster.md)

If you'd like to onboard the Argo CD feel free to either follow [this doc](https://github.com/operate-first/argocd-apps/blob/main/docs/onboard_team_to_argocd.md) or create an issue at [operate-first/argocd-apps](https://github.com/operate-first/argocd-apps)

**Comment by tumido** [comment]
@larsks I can't close tickets in this or, can you please do that?

**Comment by eletonia** [comment]
@tumido Thank you! I was able to log into the MOC CNV cluster but I cannot access the `mesh-for-data` namespace 

```
Logged into "https://api.cnv.massopen.cloud:6443" as "elentonia@gmail.com" using the token provided.
You don't have any projects. Contact your system administrator to request a project.
$ oc get ns
Error from server (Forbidden): namespaces is forbidden: User "elentonia@gmail.com" cannot list resource "namespaces" in API group "" at the cluster scope
$ oc project mesh-for-data
error: You are not a member of project "mesh-for-data".
You are not a member of any projects. You can request a project to be created with the 'new-project' command.
To see projects on another server, pass '--server=<server>'.
```

**Comment by HumairAK** [comment]
Taking a look

**Comment by HumairAK** [comment]
Looks like we added the user `tonia.elengikal at ibm.com` as per the email requested, but the ocp user is `elentonia at gmail.com`, I'll add this user as well.

**Comment by HumairAK** [comment]
@eletonia can you try again and let us know here if it works. Thanks.

**Comment by eletonia** [comment]
@HumairAK Yes I have access now, thanks!
```
$ oc project
Using project "mesh-for-data" on server "https://api.cnv.massopen.cloud:6443"
```

**Comment by HumairAK** [comment]
Great, np!
